Use a tmp makefile for rivet-buildplugin

diff --git a/bin/rivet-buildplugin.in b/bin/rivet-buildplugin.in
--- a/bin/rivet-buildplugin.in
+++ b/bin/rivet-buildplugin.in
@@ -9,7 +9,7 @@ PROG=$(basename $0)
 let num_jobs=$(getconf _NPROCESSORS_ONLN)
 
 function usage {
-    cat <<-EOF
+	cat <<-EOF
 		$PROG: 
 		compile a Rivet analysis plugin library from one or more sources
 
@@ -29,6 +29,7 @@ function usage {
 		  -r | --with-root: add ROOT link options (requires root-config on system)
 		  -n | --cmd | --dry-run: 
 		                    just print the generated commands, do not execute
+		  -k | --keep:      keep intermediate files
 
 	EOF
 }
@@ -38,28 +39,30 @@ function usage {
 args=()
 for arg
 do
-    case "$arg" in
-       # translate our long options
-       --help            ) args+=("-h");;
-       --with-root       ) args+=("-r");;
-       --cmd | --dry-run ) args+=("-n");;
-       # pass through anything else
+	case "$arg" in
+	   # translate our long options
+	   --help            ) args+=("-h");;
+	   --with-root       ) args+=("-r");;
+	   --cmd | --dry-run ) args+=("-n");;
+	   --keep            ) args+=("-k");;
+	   # pass through anything else
 	   *                 ) args+=("$arg");;
-    esac
+	esac
 done
 # reset the translated args
 set -- "${args[@]}"
 
 # now we can process with getopt
-while getopts ":hrnj:" opt; do
-    case $opt in
-        h)  usage; exit 0 ;;
+while getopts ":hj:rnk" opt; do
+	case $opt in
+		h)  usage; exit 0 ;;
 		j)  num_jobs=$OPTARG ;;
-        r)  with_root=yes ;;
-        n)  only_show=yes ;;
-        \?) echo "Unknown option -$OPTARG" >&2; exit 1 ;;
+		r)  with_root=yes ;;
+		n)  only_show=yes ;;
+		k)  keep_tmps=yes ;;
+		\?) echo "Unknown option -$OPTARG" >&2; exit 1 ;;
 		:)  echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
-    esac
+	esac
 done
 # remove options
 shift $((OPTIND-1))
@@ -88,17 +91,17 @@ libname="$1"
 match1=$(basename "$libname" | egrep '^.*\.so')
 match2=$(basename "$libname" | egrep '^Rivet.*\.so')
 if test -n "$match1"; then
-    if test -z "$match2"; then
-        echo "Library name '$libname' does not have the required 'Rivet*.so' name pattern" >&2
-        exit 1
-    fi
-    ## If we're using the first arg as the library name, shift it off the positional list
-    shift
+	if test -z "$match2"; then
+		echo "Library name '$libname' does not have the required 'Rivet*.so' name pattern" >&2
+		exit 1
+	fi
+	## If we're using the first arg as the library name, shift it off the positional list
+	shift
 else
-    if [[ -z $only_show ]]; then
-        echo "Using default library name 'RivetAnalysis.so'"
-    fi
-    libname="RivetAnalysis.so"
+	if [[ -z $only_show ]]; then
+		echo "Using default library name 'RivetAnalysis.so'"
+	fi
+	libname="RivetAnalysis.so"
 fi
 
 # again need some args left at this point
@@ -131,17 +134,17 @@ mycxx=g++
 rivetcxx=$(which $(echo "@RIVETCXX@" | awk '{print $1}') 2> /dev/null)
 abscxx=$(which "$CXX" 2> /dev/null)
 if [[ -x "$rivetcxx" ]]; then
-    mycxx="@CXX@"
+	mycxx="@CXX@"
 elif [[ -x "$abscxx" ]]; then
-    mycxx="$CXX"
+	mycxx="$CXX"
 fi
 
 ## Get Rivet system C++ compiler flags
 if [[ -n "@AM_CXXFLAGS@" ]]; then
-    mycxxflags="@AM_CXXFLAGS@"
+	mycxxflags="@AM_CXXFLAGS@"
 fi
 if [[ -n "@RIVETCXXFLAGS@" ]]; then
-    mycxxflags="$mycxxflags @RIVETCXXFLAGS@"
+	mycxxflags="$mycxxflags @RIVETCXXFLAGS@"
 fi
 
 ## Get Rivet system C preprocessor flags (duplicating that in rivet-config.in)
@@ -179,10 +182,9 @@ fi
 
 ## Get ROOT flags if needed
 if [[ -n $with_root ]]; then
-    rootcxxflags=$(root-config --cflags 2> /dev/null)
-    rootldflags=$(root-config --libs 2> /dev/null)
+	rootcxxflags=$(root-config --cflags 2> /dev/null)
+	rootldflags=$(root-config --libs 2> /dev/null)
 fi
-
 
 
 
@@ -191,16 +193,16 @@ let idx=1
 for src in "$@"
 do
 	if [[ -s "$src" ]]; then
-	    buckets[$idx]="${buckets[$idx]} $src"
-    	let idx=(idx%$num_jobs)+1
-    else
-    	if [[ ${src:0:1} == "-" ]]; then
-    		# found a user option
-    		usercxxflags="$usercxxflags $src"
-    	else
-	    	echo "Warning: $src not found" >&2
-	    fi
-    fi
+		buckets[$idx]="${buckets[$idx]} $src"
+		let idx=(idx%$num_jobs)+1
+	else
+		if [[ ${src:0:1} == "-" ]]; then
+			# found a user option
+			usercxxflags="$usercxxflags $src"
+		else
+			echo "Warning: $src not found" >&2
+		fi
+	fi
 done
 
 # may be less than num_jobs
@@ -214,37 +216,51 @@ fi
 # loop over buckets
 for idx in $(seq 1 $num_buckets); do
 
-    # DO NOT SIMPLIFY, the OS X mktemp can't deal with suffixes directly
-    tmpfile="$(mktemp tmp.XXXXXXXX)"    
-    mv "$tmpfile" "$tmpfile.cc"
-    tmpfile="$tmpfile.cc"
+	# DO NOT SIMPLIFY, the OS X mktemp can't deal with suffixes directly
+	tmpfile="$(mktemp tmp.XXXXXXXX)"    
+	mv "$tmpfile" "$tmpfile.cc"
+	tmpfile="$tmpfile.cc"
  
-    for i in $(echo ${buckets[$idx]}) # find the real way to do this
-    do
-        echo "#line 1 \"$i\"" >> "$tmpfile"
-        cat "$i" >> "$tmpfile"
-    done
+	for i in $(echo ${buckets[$idx]}) # find the real way to do this
+	do
+		echo "#line 1 \"$i\"" >> "$tmpfile"
+		cat "$i" >> "$tmpfile"
+	done
 
-    if [[ -s "$tmpfile" ]]; then
-        srcnames[$idx]="$tmpfile"
-        ## Build
-        cmd="$mycxx -c $shared_flags $mycppflags $mycxxflags $rootcxxflags $usercxxflags $tmpfile"
-        echo $cmd
-        if [[ -z $only_show ]]; then
-            eval $cmd &
-        fi
-    fi
+	if [[ -s "$tmpfile" ]]; then
+		srcnames[$idx]="$tmpfile"
+	fi
 done
-
-echo "=== Waiting for ${#srcnames[@]} compilation(s) before linking ==="
-wait # for subprocesses to complete
 
 objnames=("${srcnames[@]/.cc/.o}")
 
-cmd="$mycxx -o \"$libname\" ${objnames[@]} $shared_flags $mycxxflags $myldflags $rootldflags -lRivet $usercxxflags"
-echo $cmd
+
+tmpmakefile=$(mktemp Makefile.tmp.XXXXXXXXXX)
+
+cat > "$tmpmakefile" <<EOF
+CXX = $mycxx
+
+CXXFLAGS = $shared_flags $mycxxflags $rootcxxflags $usercxxflags
+
+CPPFLAGS = $mycppflags
+
+LDFLAGS = $myldflags $rootldflags -lRivet
+
+$libname : ${objnames[@]}
+	\$(CXX) \$^  \$(CXXFLAGS) \$(LDFLAGS) -o \$@ 
+
+%.o : %.cc
+	\$(CXX) \$(CXXFLAGS) \$(CPPFLAGS) -c -o \$@ \$^
+EOF
+
 if [[ -z $only_show ]]; then
-    eval $cmd
+	make -j ${num_jobs} -f "$tmpmakefile"
+else
+	echo "Contents of $tmpmakefile"
+	echo "====="
+	cat "$tmpmakefile"
 fi
 
-rm -f "${srcnames[@]}" "${objnames[@]}"
+if [[ -z $keep_tmps ]]; then
+	rm -f "${srcnames[@]}" "${objnames[@]}" "$tmpmakefile"
+fi
