Tweaks to try and include YODA's PYTHONPATH in the rivetenv PYTHONPATH if possible

diff --git a/rivetenv.sh.in b/rivetenv.sh.in
--- a/rivetenv.sh.in
+++ b/rivetenv.sh.in
@@ -1,11 +1,15 @@
-# These variables need to exist
+## These variables need to exist
 prefix=@prefix@
 exec_prefix=@exec_prefix@
 datarootdir=@datarootdir@
 
+## Try to automatically work out the YODA Python path
+(which yoda-config > /dev/null) && YODA_PYTHONPATH=`yoda-config --pythonpath` || \
+    echo "yoda-config could not be found: you may need to manually set paths to libYODA and the yoda Python package" 1>&2
+
 export PATH="$exec_prefix/bin:$PATH"
 export @LIBPATHVARNAME@="@libdir@:@HEPMCLIBPATH@:@FASTJETLIBPATH@:@YAML_CPPLIBPATH@:$@LIBPATHVARNAME@"
-export PYTHONPATH="@RIVET_PYTHONPATH@:$PYTHONPATH"
+export PYTHONPATH="@RIVET_PYTHONPATH@:$YODA_PYTHONPATH:$PYTHONPATH"
 
 export TEXMFHOME="@datadir@/Rivet/texmf:$TEXMFHOME"
 export HOMETEXMF="@datadir@/Rivet/texmf:$HOMETEXMF"
